In [1]:
import numpy as np
import pandas as pd

data = pd.read_csv("weather.csv")
data.head()

C:\Users\Anri Wang\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012 2:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012 3:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog

In [2]:
data.shape

(8784, 8)

In [3]:
data.isnull().sum()

Date/Time           0
Temp_C              0
Dew Point Temp_C    0
Rel Hum_%           0
Wind Speed_km/h     0
Visibility_km       0
Press_kPa           0
Weather             0
dtype: int64

In [4]:
data.dtypes

Date/Time            object
Temp_C              float64
Dew Point Temp_C    float64
Rel Hum_%             int64
Wind Speed_km/h       int64
Visibility_km       float64
Press_kPa           float64
Weather              object
dtype: object

In [5]:
data['Weather'].unique()

array(['Fog', 'Freezing Drizzle,Fog', 'Mostly Cloudy', 'Cloudy', 'Rain',
       'Rain Showers', 'Mainly Clear', 'Snow Showers', 'Snow', 'Clear',
       'Freezing Rain,Fog', 'Freezing Rain', 'Freezing Drizzle',
       'Rain,Snow', 'Moderate Snow', 'Freezing Drizzle,Snow',
       'Freezing Rain,Snow Grains', 'Snow,Blowing Snow', 'Freezing Fog',
       'Haze', 'Rain,Fog', 'Drizzle,Fog', 'Drizzle',
       'Freezing Drizzle,Haze', 'Freezing Rain,Haze', 'Snow,Haze',
       'Snow,Fog', 'Snow,Ice Pellets', 'Rain,Haze', 'Thunderstorms,Rain',
       'Thunderstorms,Rain Showers', 'Thunderstorms,Heavy Rain Showers',
       'Thunderstorms,Rain Showers,Fog', 'Thunderstorms',
       'Thunderstorms,Rain,Fog',
       'Thunderstorms,Moderate Rain Showers,Fog', 'Rain Showers,Fog',
       'Rain Showers,Snow Showers', 'Snow Pellets', 'Rain,Snow,Fog',
       'Moderate Rain,Fog', 'Freezing Rain,Ice Pellets,Fog',
       'Drizzle,Ice Pellets,Fog', 'Drizzle,Snow', 'Rain,Ice Pellets',
       'Drizzle,Snow,Fog', 'Rain,Snow Grains', 'Rain,Snow,Ice Pellets',
       'Snow Showers,Fog', 'Moderate Snow,Blowing Snow'], dtype=object)

In [6]:
data.nunique()

Date/Time           8784
Temp_C               533
Dew Point Temp_C     489
Rel Hum_%             83
Wind Speed_km/h       34
Visibility_km         24
Press_kPa            518
Weather               50
dtype: int64

In [7]:
data.count()

Date/Time           8784
Temp_C              8784
Dew Point Temp_C    8784
Rel Hum_%           8784
Wind Speed_km/h     8784
Visibility_km       8784
Press_kPa           8784
Weather             8784
dtype: int64

In [29]:
data['Weather'].value_counts().sort_values(ascending=True)

Weather Condition
Freezing Rain,Snow Grains                     1
Rain Showers,Fog                              1
Thunderstorms,Moderate Rain Showers,Fog       1
Snow Pellets                                  1
Rain,Snow,Fog                                 1
Moderate Rain,Fog                             1
Thunderstorms,Heavy Rain Showers              1
Drizzle,Ice Pellets,Fog                       1
Thunderstorms,Rain,Fog                        1
Rain,Ice Pellets                              1
Rain,Snow Grains                              1
Freezing Rain,Ice Pellets,Fog                 1
Drizzle,Snow                                  2
Freezing Rain,Haze                            2
Moderate Snow,Blowing Snow                    2
Rain Showers,Snow Showers                     2
Thunderstorms                                 2
Thunderstorms,Rain Showers,Fog                3
Thunderstorms,Rain                            3
Rain,Haze                                     3
Freezing Drizzle,Haze                         3
Snow Showers,Fog                              4
Freezing Rain,Fog                             4
Rain,Snow,Ice Pellets                         4
Moderate Snow                                 4
Freezing Fog                                  4
Snow,Haze                                     5
Freezing Drizzle,Fog                          6
Snow,Ice Pellets                              6
Freezing Drizzle                              7
Freezing Drizzle,Snow                        11
Freezing Rain                                14
Drizzle,Snow,Fog                             15
Haze                                         16
Thunderstorms,Rain Showers                   16
Rain,Snow                                    18
Snow,Blowing Snow                            19
Snow,Fog                                     37
Drizzle                                      41
Snow Showers                                 60
Drizzle,Fog                                  80
Rain,Fog                                    116
Fog                                         150
Rain Showers                                188
Rain                                        306
Snow                                        390
Clear                                      1326
Cloudy                                     1728
Mostly Cloudy                              2069
Mainly Clear                               2106
Name: count, dtype: int64

In [9]:
data.columns

Index(['Date/Time', 'Temp_C', 'Dew Point Temp_C', 'Rel Hum_%',
       'Wind Speed_km/h', 'Visibility_km', 'Press_kPa', 'Weather'],
      dtype='object')

In [10]:
data['Wind Speed_km/h'].unique()

array([ 4,  7,  6,  9, 15, 13, 20, 22, 19, 24, 30, 35, 39, 32, 33, 26, 44,
       43, 48, 37, 28, 17, 11,  0, 83, 70, 57, 46, 41, 52, 50, 63, 54,  2],
      dtype=int64)

In [11]:
data[data['Weather'] == 'Clear']['Weather'].count()

1326

In [12]:
data[data['Wind Speed_km/h'] == 4]['Wind Speed_km/h'].count()

474

In [13]:
data = data.rename(columns = {'Weather':'Weather Condition'})
data.head()

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012 2:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012 3:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog

In [14]:
data['Visibility_km'].mean().round(2)

27.66

In [15]:
data['Press_kPa'].std().round(2)

0.84

In [16]:
data['Rel Hum_%'].var().round(2)

286.25

In [17]:
data[data['Weather Condition'].str.contains('Snow')].head()

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
41,1/2/2012 17:00,-2.1,-9.5,57,22,25.0,99.66,Snow Showers
44,1/2/2012 20:00,-5.6,-13.4,54,24,25.0,100.07,Snow Showers
45,1/2/2012 21:00,-5.8,-12.8,58,26,25.0,100.15,Snow Showers
47,1/2/2012 23:00,-7.4,-14.1,59,17,19.3,100.27,Snow Showers
48,1/3/2012 0:00,-9.0,-16.0,57,28,25.0,100.35,Snow Showers

In [18]:
data[(data['Wind Speed_km/h'] > 24) & (data['Visibility_km'] == 25)]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
23,1/1/2012 23:00,5.3,2.0,79,30,25.0,99.31,Cloudy
24,1/2/2012 0:00,5.2,1.5,77,35,25.0,99.26,Rain Showers
25,1/2/2012 1:00,4.6,0.0,72,39,25.0,99.26,Cloudy
26,1/2/2012 2:00,3.9,-0.9,71,32,25.0,99.26,Mostly Cloudy
27,1/2/2012 3:00,3.7,-1.5,69,33,25.0,99.30,Mostly Cloudy
...,...,...,...,...,...,...,...,...
8705,12/28/2012 17:00,-8.6,-12.0,76,26,25.0,101.34,Mainly Clear
8753,12/30/2012 17:00,-12.1,-15.8,74,28,25.0,101.26,Mainly Clear
8755,12/30/2012 19:00,-13.4,-16.5,77,26,25.0,101.47,Mainly Clear
8759,12/30/2012 23:00,-12.1,-15.1,78,28,25.0,101.52,Mostly Cloudy
8760,12/31/2012 0:00,-11.1,-14.4,77,26,25.0,101.51,Cloudy

In [19]:
data.groupby('Weather Condition').mean(numeric_only=True).round(2).head()

,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa
Weather Condition,,,,,,
Clear,6.83,0.09,64.50,10.56,30.15,101.59
Cloudy,7.97,2.38,69.59,16.13,26.63,100.91
Drizzle,7.35,5.50,88.24,16.10,17.93,100.44
"Drizzle,Fog",8.07,7.03,93.28,11.86,5.26,100.79
"Drizzle,Ice Pellets,Fog",0.40,-0.70,92.00,20.00,4.00,100.79

In [20]:
data[data['Weather Condition'].str.contains('Fog')]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012 2:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012 3:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog
...,...,...,...,...,...,...,...,...
8739,12/30/2012 3:00,-9.1,-10.4,90,11,3.6,100.30,"Snow,Fog"
8740,12/30/2012 4:00,-9.3,-10.6,90,13,9.7,100.28,"Snow,Fog"
8741,12/30/2012 5:00,-9.1,-10.4,90,11,4.0,100.32,"Snow,Fog"
8742,12/30/2012 6:00,-9.3,-10.8,89,17,8.0,100.39,"Snow,Fog"
8770,12/31/2012 10:00,-7.4,-8.9,89,4,6.4,101.05,"Snow,Fog"

In [21]:
data[((data['Weather Condition'] == 'Clear') & (data['Rel Hum_%'] > 50)) | (data['Visibility_km'] > 40)]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
106,1/5/2012 10:00,-6.0,-10.0,73,17,48.3,100.45,Mainly Clear
107,1/5/2012 11:00,-5.6,-10.2,70,22,48.3,100.41,Mainly Clear
108,1/5/2012 12:00,-4.7,-9.6,69,20,48.3,100.38,Mainly Clear
109,1/5/2012 13:00,-4.4,-9.7,66,26,48.3,100.40,Mainly Clear
110,1/5/2012 14:00,-5.1,-10.7,65,22,48.3,100.46,Mainly Clear
...,...,...,...,...,...,...,...,...
8749,12/30/2012 13:00,-12.4,-16.2,73,37,48.3,100.92,Mostly Cloudy
8750,12/30/2012 14:00,-11.8,-16.1,70,37,48.3,100.96,Mainly Clear
8751,12/30/2012 15:00,-11.3,-15.6,70,32,48.3,101.05,Mainly Clear
8752,12/30/2012 16:00,-11.4,-15.5,72,26,48.3,101.15,Mainly Clear
8756,12/30/2012 20:00,-13.8,-16.5,80,24,25.0,101.52,Clear

In [22]:
data.head()

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012 2:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012 3:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog

In [23]:
data.groupby(['Visibility_km','Weather Condition'])['Press_kPa'].mean().reset_index()

     Visibility_km Weather Condition   Press_kPa
0              0.2               Fog  102.260000
1              0.2      Freezing Fog  102.260000
2              0.4               Fog  100.933333
3              0.6               Fog  101.493333
4              0.6     Moderate Snow   99.880000
..             ...               ...         ...
238           48.3      Mainly Clear  101.334776
239           48.3     Mostly Cloudy  101.212392
240           48.3              Rain  101.215000
241           48.3      Rain Showers  101.085000
242           48.3      Snow Showers  100.280000

[243 rows x 3 columns]

In [24]:
data.groupby(['Visibility_km','Weather Condition']).agg({'Rel Hum_%':'max',
                                                        'Wind Speed_km/h':'min',
                                                        'Dew Point Temp_C':'mean'}).reset_index()

,Visibility_km,Weather Condition,Rel Hum_%,Wind Speed_km/h,Dew Point Temp_C
0,0.2,Fog,100,0,1.371429
1,0.2,Freezing Fog,98,4,-0.400000
2,0.4,Fog,100,4,8.666667
3,0.6,Fog,100,4,3.866667
4,0.6,Moderate Snow,83,33,-7.300000
...,...,...,...,...,...
238,48.3,Mainly Clear,92,0,4.492308
239,48.3,Mostly Cloudy,100,0,3.057309
240,48.3,Rain,76,0,4.200000
241,48.3,Rain Showers,45,7,6.850000
242,48.3,Snow Showers,60,35,-9.600000

In [39]:
# Count occurrences of each class
class_counts = data['Weather Condition'].value_counts()

# Keep only rows where class appears more than once
data = data[data['Weather Condition'].isin(class_counts[class_counts > 10].index)]

In [41]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from xgboost import XGBClassifier


# Features and target
features = ['Temp_C', 'Dew Point Temp_C', 'Rel Hum_%', 'Wind Speed_km/h', 'Visibility_km', 'Press_kPa']
target = 'Weather Condition'

X = data[features]
y = data[target]

# Encode the target labels
le = LabelEncoder()
y_encoded = le.fit_transform(y)

# Normalize features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Train/test split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y_encoded, test_size=0.2, random_state=42, stratify=y_encoded)

# Initialize models
models = {
    'Random Forest': RandomForestClassifier(),
    'XGBoost': XGBClassifier(use_label_encoder=False, eval_metric='mlogloss'),
    'Logistic Regression': LogisticRegression(max_iter=1000),
    'Neural Net (MLP)': MLPClassifier(max_iter=500)
}

# Train, predict, and evaluate
accuracy_results = {}
for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    accuracy_results[name] = acc
    print(f"{name} Accuracy: {acc:.4f}")

# Optional: Show results as a sorted table
results_data = pd.DataFrame(list(accuracy_results.items()), columns=["Model", "Accuracy"]).sort_values("Accuracy", ascending=False)
print("\nAccuracy Comparison:")
print(results_data)

Random Forest Accuracy: 0.5362

C:\Users\Anri Wang\anaconda3\Lib\site-packages\xgboost\core.py:158: UserWarning: [20:39:49] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-08cbc0333d8d4aae1-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

XGBoost Accuracy: 0.4902
Logistic Regression Accuracy: 0.3743
Neural Net (MLP) Accuracy: 0.4173

Accuracy Comparison:
                 Model  Accuracy
0        Random Forest  0.536165
1              XGBoost  0.490241
3     Neural Net (MLP)  0.417336
2  Logistic Regression  0.374282